version: "3.9"

services:
  floofybot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
    networks:
      - floofybot-network
    restart:
      always

networks:
  floofybot-network:
